# lightning.pytorch==2.1.1
custom_modules_path: ./thor_terratorch_ext # Path relative to where you run terratorch
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  callbacks: []
  max_epochs: 0

data:
  class_path: terratorch.datamodules.GenericNonGeoSegmentationDataModule
  init_args:
    batch_size: 4
    check_stackability: false
    num_workers: 4
    dataset_bands:
      - COASTAL_AEROSOL
      - BLUE
      - GREEN
      - RED
      - RED_EDGE_1
      - RED_EDGE_2
      - RED_EDGE_3
      - NIR_BROAD
      - NIR_NARROW
      - WATER_VAPOR
      - CIRRUS
      - SWIR_1
      - SWIR_2
    no_data_replace: 0
    num_classes: 2
    img_grep: "*_S2Hand.tif"

    train_data_root: none
    val_data_root: none
    test_data_root: none
    predict_data_root: /nr/bamjo/projects/fm4cs/data/sen1floods/v1.1/data/flood_events/HandLabeled/S2Hand/

    means:
      - 1626.916002243284
      - 1396.0347063125125
      - 1364.0611841716463
      - 1218.228479188586
      - 1466.0729066303797
      - 2386.9029753700133
      - 2845.6125627699353
      - 2622.9579689237808
      - 3077.482214806572
      - 486.87436781989203
      - 63.778610078115314
      - 2030.6476302373976
      - 1179.166072209676
    stds:
      - 700.1713384623788
      - 739.0945268205048
      - 735.2482387959477
      - 864.9366949997807
      - 776.8803358037292
      - 921.3683430927466
      - 1084.3734609719752
      - 1022.6341800670566
      - 1196.4425531763263
      - 336.6110543131482
      - 143.99923282248625
      - 980.8706134697641
      - 764.6083655721079

    # Transforms are shared between all image modalities (e.g. same crop area)
    # train_transform:
    #   - class_path: albumentations.RandomCrop
    #     init_args:
    #       height: 288
    #       width: 288
    #   - class_path: albumentations.D4
    #   - class_path: albumentations.pytorch.transforms.ToTensorV2

predict_output_dir: "./"

model:
  class_path: terratorch.tasks.EmbeddingGenerationTask
  init_args:
    model_args:
      backbone: thor_v1_base
      backbone_pretrained: true
      backbone_model_bands:
        # - COASTAL_AEROSOL
        - BLUE
        - GREEN
        - RED
        - RED_EDGE_1
        - RED_EDGE_2
        - RED_EDGE_3
        - NIR_BROAD
        - NIR_NARROW
        # - WATER_VAPOR
        # - CIRRUS # Not present in THOR
        - SWIR_1
        - SWIR_2
      backbone_input_params:
        ground_covers: [2880]
        flexivit_patch_size_seqs:
          - 16
      backbone_out_indices: [-1]
      necks:
        - name: THORGroupReshapeTokensToImage
          merge: "mean"
    output_format: tiff
    output_dir: "output/thor_embeddings"
    layers: [-1] # Model layers to extract embeddings from, -1 means the last layer
    embedding_pooling: null
    has_cls: False
