seed_everything: 0
custom_modules_path: ./thor_terratorch_ext # Path relative to where you run terratorch
trainer:
  accelerator: gpu
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  # logger: True # will use tensorboardlogger
  logger:
    class_path: WandbLogger
    init_args:
      name: sen1floods11_thor_S1_2880m
      project: terratorch
      save_dir: /nr/bamjo/projects/fm4cs/usr/tforgaard/terratorch_results
  callbacks:
    - class_path: RichProgressBar
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/loss
        patience: 20
        mode: min
        check_finite: false
        verbose: true

  max_epochs: 200
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
  log_every_n_steps: 1
  enable_checkpointing: true
  default_root_dir: /nr/bamjo/projects/fm4cs/usr/tforgaard/terratorch_results/results
data:
  class_path: GenericNonGeoSegmentationDataModule
  init_args:
    batch_size: 4
    num_workers: 4
    dataset_bands:
      - VV
      - VH
    rgb_indices: [0, 1, 1]
    train_data_root: /nr/bamjo/projects/fm4cs/data/sen1floods/v1.1/data/flood_events/HandLabeled/S1Hand/
    train_label_data_root: /nr/bamjo/projects/fm4cs/data/sen1floods/v1.1/data/flood_events/HandLabeled/LabelHand
    val_data_root: /nr/bamjo/projects/fm4cs/data/sen1floods/v1.1/data/flood_events/HandLabeled/S1Hand/
    val_label_data_root: /nr/bamjo/projects/fm4cs/data/sen1floods/v1.1/data/flood_events/HandLabeled/LabelHand
    test_data_root: /nr/bamjo/projects/fm4cs/data/sen1floods/v1.1/data/flood_events/HandLabeled/S1Hand/
    test_label_data_root: /nr/bamjo/projects/fm4cs/data/sen1floods/v1.1/data/flood_events/HandLabeled/LabelHand
    # these must be obtained by running terratorch/examples/scripts/convert_sen1floods11_splits.py on the original split csv files
    train_split: /nr/bamjo/projects/fm4cs/data/sen1floods/v1.1/splits/flood_handlabeled/flood_train_data.txt
    test_split: /nr/bamjo/projects/fm4cs/data/sen1floods/v1.1/splits/flood_handlabeled/flood_test_data.txt
    val_split: /nr/bamjo/projects/fm4cs/data/sen1floods/v1.1/splits/flood_handlabeled/flood_valid_data.txt
    img_grep: "*_S1Hand.tif"
    label_grep: "*_LabelHand.tif"
    no_label_replace: -1
    no_data_replace: 0
    check_stackability: false
    means:
      - -10.184386565394322
      - -16.89525461597349
    stds:
      - 4.255338143340657
      - 5.290564988051755

    num_classes: 2

    # Transforms are shared between all image modalities (e.g. same crop area)
    train_transform:
      - class_path: albumentations.RandomCrop
        init_args:
          height: 288
          width: 288
      - class_path: albumentations.D4
      - class_path: albumentations.pytorch.transforms.ToTensorV2

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    tiled_inference_on_testing: true
    tiled_inference_on_validation: true
    model_args:
      backbone_pretrained: true
      backbone: thor_v1_base
      backbone_input_params:
        ground_covers: [2880]
        flexivit_patch_size_seqs: 
          - 8
      backbone_out_indices: [-1]
      backbone_model_bands:
        - VV
        - VH
      decoder: FCNDecoder
      decoder_channels: 256
      decoder_num_convs: 4
      num_classes: 2
      head_dropout: 0.1
      head_channel_list:
        - 256
      necks:
        - name: THORGroupReshapeTokensToImage
    loss: ce
    ignore_index: -1
    class_weights:
      - 0.3
      - 0.7
    freeze_backbone: true
    freeze_decoder: false
    model_factory: EncoderDecoderFactory
    tiled_inference_parameters:
      h_crop: 288
      h_stride: 256
      w_crop: 288
      w_stride: 256
      average_patches: true
      batch_size: 4
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 6e-5
    weight_decay: 0.05
lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    monitor: val/loss
